version: '3.8'

services:
  db:
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # For application please uncomment POSTGRES_PASSWORD and 
      # set a password (preferably with secrets or .env) and
      # comment out the POSTGRES_HOST_AUTH_METHOD variable
      #- POSTGRES_PASSWORD=""
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=<name_of_user>
      - POSTGRES_HOST=<host_name>
      - POSTGRES_DB=<database_name>
      - POSTGRES_PORT=<port_number>

    ports:
      - "5432:5432"
    networks:
      - app_network

  app:
    build: .
    command: uvicorn app.main:app --reload --port 80 --host 0.0.0.0
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
